### ISSUE TITLE
我这里 ts 推断 会报错：需要 commit("common/set_loading")才能不提示错误 但是 实际运行时 控制台会报错 提示 没有相关的mutation。一下午没能理解

### ISSUE THREAD

**Issue by yao8384** [mk-site/vite-vue3-template#1]
https://github.com/mk-site/vite-vue3-template/blob/7123e97c86832d17a64befc67462c1efd5df220f/src/store/modules/common.ts#L41

**Comment by mk-site** [comment]
![image](https://user-images.githubusercontent.com/21324226/129675962-2c85132d-5622-4162-a54a-b98b061ef490.png)

问题已修复，增加了ActionContextCommit推断类型

**Comment by yao8384** [comment]
😆 多谢大佬
